source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               libs/,\
               libs/jackson-annotations-2.20.jar,\
               libs/jackson-core-2.20.1.jar,\
               libs/jackson-databind-2.20.1.jar
