bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               fragment.e4xmi,\
               libs/diff-match-patch-1.2.jar,\
               libs/immutables-exceptions-1.2.jar,\
               libs/jackson-annotations-2.20.jar,\
               libs/jackson-core-2.20.1.jar,\
               libs/jackson-databind-2.20.1.jar,\
               libs/jackson-dataformat-yaml-2.17.2.jar,\
               libs/jackson-datatype-jdk8-2.20.0.jar,\
               libs/jinjava-2.8.2.jar,\
               libs/mjson-1.4.2.jar,\
               libs/re2j-1.5.jar
source.. = src/
output.. = bin/
